### ISSUE TITLE
arm32 JDK12 builds failing to download gradle (certificate error)

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#1004]
Ref: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk12u/job/jdk12u-linux-arm-hotspot/
Worked last week (including the download of gradle) but today I'm getting:
```
Downloading https://services.gradle.org/distributions/gradle-5.2.1-bin.zip

Exception in thread "main" javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: signature check failed
    at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
```

**Comment by jgneff** [comment]
To work around the problem temporarily while building natively in my local environment, I use JDK 12 as the boot JDK instead of JDK 11.

* **JDK 11:** OpenJDK11U-jdk_arm_linux_hotspot_11.0.3_7.tar.gz (fails)
* **JDK 12:** OpenJDK12U-jdk_arm_linux_hotspot_12.0.1_12.tar.gz (works)

If I remember correctly when I did this yesterday, after a successful pass, you can run the build a second time with JDK 11 as the boot JDK after all the prerequisites have been downloaded in the first pass.

**Comment by jperedadnr** [comment]
Today I was trying on my Raspberry Pi the 11.0.1+13 version that I had installed. It was working fine a few months ago, but today I was refreshing my gradle build, and when trying to retrieve a new version of one of the plugins, I noticed that gradle failed to access any HTTPS resource, with the above exception. 

I've tried installing 11.0.4+11 and 12.0.2+10 (from releases, and also latest build from today) to no avail. 

As it looks like some certificate has expired, my question is: Can we say that any Java version for ARM 32 bits from AdoptOpenJDK won't work, regarding https, until this bug is fixed?

Since the milestone for this issue has been moved several times, when can we expect a fix? And would this fix be only applied to new JDK versions?

**Comment by sxa555** [comment]
I'll aim to get this looked at in the nexty week - it's not affecting our current builds but it's also not re-downloading gradle ...

**Comment by sxa555** [comment]
Haven't had time to get back to this as I expected - If @Willsparker gets some time he can work on it as he has on eof my raspberry pis sitting on his desk ;-)

**Comment by Willsparker** [comment]
@johnoliver Does #1007 fix this issue?

**Comment by johnoliver** [comment]
It should do yes, are the builds currently working?

**Comment by Willsparker** [comment]
The last one to run did - and I suppose we don't build JDK12 much anymore anyway :-) https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk12u/job/jdk12u-linux-arm-hotspot/202/console

**Comment by sxa555** [comment]
JDK13 also appears to be ok, so on that basis I'll close this. Thanks
