### ISSUE TITLE
JDK8 OpenJ9 builds not using native crypto

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-build#1039]
**Platform:**
linux

**Architecture:**
x64

FYI @sxa555 

There appear to be some changes to build scripts which have broken JDK8 OpenJ9 builds from using native crypto (openssl) library.  Other platforms seem fine, JDK11 seems fine.

Failed job:
https://ci.adoptopenjdk.net/view/Test_functional/job/openjdk8_j9_functionaltest_x86-64_linux/68/tapResults/

Output from test:
 [OUT] Crypto test COMPLETED
 [ERR] Warning: Native crypto library load failed. Using Java crypto implementation
 [ERR] Warning: Native crypto library load failed. Using Java crypto implementation
>> Success condition was not found: [Output match: using native crypto library]

**Comment by sxa555** [comment]
That failure is on Debian 8 which appears to ship with openssl 1.0.1t which is not supported by the OpenJ9 SSL code.

While we could install 1.0.2 on there (The same issue exists on RHEL6 and since that's our build system we have on there - https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/760) it becomes a matter of what we want to support, as we are not reshipping openssl libraries ourselves on Linux platforms.

**Comment by smlambert** [comment]
Openssl 1.0.2 is the LTS version which is likely why it was (arbitrarily) selected as the one supported by OpenJ9 ssl code (I am wondering if Openssl 1.0.1 is patched on Debian/RHEL6).  Will raise discussion in OpenJ9, re: lowest common denominator of supported version.

**Comment by sxa555** [comment]
I'm privately building a version of OpenJ9/JDK8 at the moment with the version checks disabled. This will allow us to at least load with the older version.

**Comment by sxa555** [comment]
@smlambert Is this still an issue? According to https://github.com/eclipse/openj9-docs/issues/260 support was put in for supporting 1.0.1. I'm going to close this for now as I believe it's fixed. We are, however, looking at adding 1.0.2 into our Debian playbooks going forwards - see https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/1021/files#diff-2fe4aec9807df5d1be9c28ca7c6d32d5 (I have no knowledge of how the existing Debian machines were set up since George has repeatedly failed to send us the set up docs so we're redeveloping them from scratch for Debian).

**Comment by smlambert** [comment]
Thanks @sxa555 !  I think this is addressed, will open a fresh separate issue if anything new crops up.
