### ISSUE TITLE
makejdk-any-platform.sh docker support is broken (Gradle-related)

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#1073]
May be other issues but at the moment gradle is unable to find a suitable JDK to use at the moment, so docker builds cannot be performed.

**Comment by Willsparker** [comment]
The version of Gradle that is being supported only seems to work using Java-8. With the fixes listed in #1216, I'm able to run `buildDocker.sh -v jdk8u` in `/openjdk-build/docker/`. Once I've altered the `../docker/jdk8/../Dockerfile` to install `zulu-8` instead of `zulu-7`, it was able to run Gradle correctly and start the build.

**Comment by Willsparker** [comment]
I was also able to correctly start building JDK10 in a docker container. This was done by installing both `zulu-8` and `zulu-9` into the container, in which the `JDK_BOOT_DIR` was detected to be `zulu-9` as required. From here, `JAVA_HOME` was set to `zulu_8`, and the build on the Docker container started.

**Comment by Willsparker** [comment]
This shouldn't be an issue anymore with #1278 :-)
