### ISSUE TITLE
Redistribution in commercial software.

### ISSUE THREAD

**Issue by terryschwarz** [AdoptOpenJDK/openjdk-build#1268]
Did a search on licensing and nothing seemed to match. To me the GPL2 with Class and Assembly Exceptions seems like a lot of mumbo jumbo that doesn't answer what I think is a simple question (however, the Class Exception portion does seems to clearly give the right to link with OpenJDK DLLs and that is not what I am questioning). 

My question is ... are we (as a commercial software vendor) allowed to actually redistribute an exploded prebuilt AdoptJDK archive (unchanged) as part of a commercial product (ie myproduct/java/...) under the license so that there is no need for end user setup and that our product can point to a known and correct release and not cause/force the whole commercial product to need to adhere to the license. I've read and re-read the license terms and I just don't see a clear answer about this.

**Comment by lumpfish** [comment]
The intent of the openjdk project is that it can be redistributed in commercial projects under the terms of the GPLv2 + classpath exception, as described here: https://openjdk.java.net/legal/gplv2+ce.html.
I am not a lawyer, but I believe that whether you can redistribute the builds along with your commercial software will depend on whether the license for your commercial software is compatible with those terms.
If you have concerns you may wish to seek legal advice.

**Comment by karianna** [comment]
> Did a search on licensing and nothing seemed to match. To me, the GPL2 with Class and Assembly Exceptions seems like a lot of mumbo jumbo that doesn't answer what I think is a simple question (however, the Class Exception portion does seem to clearly give the right to link with OpenJDK DLLs and that is not what I am questioning).
> 
> My question is ... are we (as a commercial software vendor) allowed to actually redistribute an exploded prebuilt AdoptJDK archive (unchanged) as part of a commercial product (ie myproduct/java/...) under the license so that there is no need for end-user setup and that our product can point to a known and correct release and not cause/force the whole commercial product to need to adhere to the license. I've read and re-read the license terms and I just don't see a clear answer about this.

Yes, you can.

**Comment by aiguy110** [comment]
First off, NOT A LAWYER! 

That said, I did have some help from my company's legal counsel in tracking down an answer to this question, so while stating explicitly and LOUDLY that _nothing below should be construed as legal advice_... let me post some stuff here that I would have found helpful when I first came across this Github issue googling "openjdk commercial redistribution":

I initially had a hard time comprehending the ["Classpath Exception" (CE) in the OpenJDK license](https://openjdk.org/legal/gplv2+ce.html#:~:text=%22CLASSPATH%22%20EXCEPTION%20TO,from%20your%20version.) as well. Reading back over it now, I can still see why, but I think the intent behind the exception might be simpler than I originally gave it credit for. 

Key sentence (emphasis added):
> As a special exception, the copyright holders of this library give you permission to link this library with independent 
> modules to produce an **_executable_**, regardless of the license terms of these independent modules, **_and to copy and 
> distribute the resulting executable under terms of your choice_**, provided that you also meet, for each linked 
> independent module, the terms and conditions of the license of that module.

This seems weird, right? Why would we be allowed to essentially forget about all the GPL terms and distribute works utilizing this code --possibly for a fee and without making our source code available-- when the work in question is "an executable"? Why aren't the same rights granted for, say, a library?

Something that helped me immensely was [this clarifying text](https://www.gnu.org/software/classpath/license.html#:~:text=As%20such%2C%20it,those%20programs%20directly.) found under the Classpath Exception text on GNU.org (shared with me by the previously-mentioned member of my company's legal team).
> As such, it can be used to run, create and distribute a large class of applications and applets. When GNU 
> Classpath is used unmodified as the core class library for a virtual machine, compiler for the java languge, or 
> for a program written in the java programming language it does not affect the licensing for distributing those 
> programs directly.

This clarification is talking specifically about the "GNU Classpath" software, but (I believe) it should also apply to any software whose license includes the CE (e.g. OpenJDK and AdoptJDK).

I think part of the reason this refused to sink in for me at first is that, if the naive interpretation is correct, it appears to nullify pretty much all of the GPL terms in pretty much all circumstances I can think of that matter. So what is the point of OpenJDK using the GPLv2-based license in the first place? In what circumstances _do_ you have to worry about the GPL terms? 

I _think_ that the answer is that this that the CE intentionally _does not cover_ the case where you are using code from OpenJDK (or an OpenJDK-derived Java implementation) to build your own Java implementation, and therefore any Java implementation based on OpenJDK (e.g. AdoptJDK) must also be licensed under GPLv2 (optionally inheriting the CE). My best guess at the reasoning for handling the licensing this way is that Oracle doesn't want to allow anyone to use the open-source codebase that they've led development on for years to turn around and build a closed-source product that competes with their Oracle JDK and Oracle Java SE Platform products.

So if anyone other than Oracle wants to build a closed-source Java implementation and license it for a profit, they have to start from scratch. But if you want to write an application _in Java_ you are free to license and distribute it more-or-less however you want, including distributing the binaries necessary to run your Java code, provided those binaries are built from code under a GPLv2+CE license. You're _also_ free to write a _library_ in Java and license and distribute it however you want, because that library won't need access to runtime binaries until it is incorporated into an executable application, at which point it becomes an "independent module" from the perspective of the CE.

Hope that helps someone!

_**NOTE:** I posted this mostly to try to help other worried and confused souls like myself who might come across it, but I'm far from certain I've got all of this right! If anyone sees a problem with this understanding of things, please point it out!_
