### ISSUE TITLE
Installer download does not result in a well formed pkg on macOS

### ISSUE THREAD

**Issue by JeremyCavanagh** [AdoptOpenJDK/openjdk-build#1298]
macOS High Sierra

x86_64

I just downloaded adoptopenjdk13-33. Unfortunately, when I unzipped there was no well formed package just a folder of type package. Out of interest I appended  .pkg but that also failed.

**Comment by gdams** [comment]
@JeremyCavanagh did you download the installer or the binary? When you download a `.tar.gz` it won't produce an installer. If you try to open the extracted folder it will not open unless you right click, show package contents. Closing this issue as this is expected behaviour. Please re-open if you still have issues.
