### ISSUE TITLE
AdoptOpenJDK OpenJ9 binary distributions with ASL license (+ "CLASSPATH" EXCEPTION TO THE GPL)

### ISSUE THREAD

**Issue by avermeer** [AdoptOpenJDK/openjdk-build#1375]
Hello,

I see that, currently, all AdopOpenJDK binary distributions based on OpenJ9 VM have a `LICENSE` file made of the concatenation (in that order) of:
* The  GPLv2 (GNU General Public License, version 2)
* "CLASSPATH" EXCEPTION TO THE GPL

I see two limitations with this situation:
1. GPLv2 is not seen by the Apache Foundation as being compatible with ASL 2.0 (Apache License 2.0) as documented [here](https://www.apache.org/licenses/GPL-compatibility.html).
2. Some commercial projects that could embed AdoptOpenJDK OpenJ9 binaries to simplify installation can consider it as impossible given the "copyleft" nature of GPLv2.

A nice solution to both issues could be to take advantage of [OpenJ9 license](https://github.com/eclipse/openj9/blob/master/LICENSE), stating that OpenJ9 can redistributed under ASL 2.0.

Also, I noted that [AdoptOpenJDK build scripts have ASL 2.0 license](https://adoptopenjdk.net/about.html).

Of course, the `LICENSE` file of AdopOpenJDK binary distributions based on OpenJ9 with ASL 2.0 license would also need to include the licensing terms corresponding to the "CLASSPATH" EXCEPTION TO THE GPL in addition to ASL 2.0, because the Java Standard Libraries have this license, but this later license is hopefully not a copyleft one.

How about this proposal?

**Notes:**
1. My understanding is that this proposal not applicable to AdoptOpenJDK binary distributions based on HotSpot, because HotSpot sources include material with various licenses, including GPLv3, which is even less ASL 2.0 compatible. So this is why I make it clear that this request is only for OpenJ9-based distributions.
2. From the licenses, I have the feeling that one could redistribute AdoptOpenJDK OpenJ9 binary distributions replacing the LICENSE file located in the root directory of the binary archive with a LICENSE made with a concatenation of ASL 2.0 and "CLASSPATH" EXCEPTION TO THE GPL. Or am I missing something?

Kind regards,
Alexandre

**Comment by karianna** [comment]
We are a downstream provider of OpenJDK and Eclipse OpenJ9 and cannot change those licenses.

**Comment by mstoodle** [comment]
@avermeer standard IANAL disclaimer, but I'll try to pass along my understanding which hopefully doesn't lead too far astray.

When one builds Eclipse OpenJ9 with OpenJDK, you must take OpenJ9 under the EPLv2 license which explicitly has secondary compatibility for GPLV2+CE as well as GPLv2 with the OpenJDK Assembly exception. You can see the SPDX id for this license in the header of every source file in Eclipse OpenJ9.

It is true that you can also choose to take Eclipse OpenJ9 under AL2, but as you've pointed out, you may not be on on solid legal ground to then combine it with OpenJDK.

Eclipse OpenJ9 and Eclipse OMR have the same license to facilitate moving materials (docs, code, etc.) between the two projects. Because it is intended for broader use than "only" combination with OpenJDK, Eclipse OMR purposefully has more licensing flexibility.

So Eclipse OMR is really the origin or and use case for the AL2 licensing option, and Eclipse OpenJ9 simply matches it to allow us to easily move materials back and forth between the two projects no matter who originally contributed those materials.

Hope that helps!

**Comment by avermeer** [comment]
Standard IANAL too on my side, and see on-going discussion at OpenJ9 side: https://github.com/eclipse/openj9/issues/7516#issuecomment-552248580.

Maybe there's some hope?
