### ISSUE TITLE
JDK-Next git rev-list failing tags

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-build#1680]
**Platform:**
Windows
**Architecture:**
x64

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-hotspot has been failing to pick up tags in the nightlies since 16/04/2020. 

Failing code: https://github.com/AdoptOpenJDK/openjdk-build/blob/995c157903452e2c10751ab196567f281ff7fcd4/sbin/build.sh#L646

```
Pulling latest tags and getting the latest update version using git fetch -q --tags --depth=1
NOTE: This can take quite some time!  Please be patient
From /cygdrive/j/jenkins/tmp/workspace/./build//src
 * branch                  HEAD       -> FETCH_HEAD
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=<n>
    --max-age=<epoch>
    --min-age=<epoch>
    --sparse
    --no-merges
    --min-parents=<n>
    --no-min-parents
    --max-parents=<n>
    --no-max-parents
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=<n> | --no-abbrev
    --abbrev-commit
    --left-right
    --count
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
WARNING: Failed to identify latest tag in the repository
Unable to detect git tag, exiting...
```

**Comment by M-Davies** [comment]
Next build looks ok https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-hotspot/81/

**Comment by karianna** [comment]
@M-Davies So it picked up the tag as you'd expect?

**Comment by M-Davies** [comment]
It did. The build failed, but for a different reason. I'll leave this open till tomorrow as it may be an intermittent thing.

**Comment by M-Davies** [comment]
Next build failed with original error https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-hotspot/82/console

**Comment by M-Davies** [comment]
Next build failing with original error https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-hotspot/83/console

@Willsparker Can you take a look at this when you get min? 🙂

**Comment by Willsparker** [comment]
I've had a brief look and the only reason I could find for it being intermittent is that it only fails when the build doesn't re-clone the `src` repository. 
I'll have a bit more of an in-depth look when I get a chance :-)

**Comment by Willsparker** [comment]
Alright - the reason for the error message is due to this: 
https://github.com/AdoptOpenJDK/openjdk-build/blob/995c157903452e2c10751ab196567f281ff7fcd4/sbin/build.sh#L658

or more specifically, the line to try and find `$firstMatchingNameFromRepo`. 

That returns nothing, as `git describe --tags $revList` returns a list of tags, all containing `jdk-11` (which are therefore removed when the list is piped into `grep "jdk-${BUILD_CONFIG[OPENJDK_FEATURE_NUMBER]}"`)

That's because it's the `jdk11` repo:  ( from https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-hotspot/83/console )
```
Retrieving cacerts file if needed
origin	https://github.com/adoptopenjdk/openjdk-jdk11u.git (fetch)
origin	https://github.com/adoptopenjdk/openjdk-jdk11u.git (push)
jdk
origin	https://github.com/adoptopenjdk/openjdk-jdk11u.git (fetch)
Resetting the git openjdk source repository at /cygdrive/j/jenkins/tmp/workspace/build/src in 10 seconds...
```
This repo is considered okay, and not removed because of this line :
https://github.com/AdoptOpenJDK/openjdk-build/blob/2041d51db738b741f2a630bc803ca1f038ef62b2/sbin/prepareWorkspace.sh#L52

Due to `${BUILD_CONFIG[OPENJDK_CORE_VERSION]}` being `jdk` and `"${BUILD_CONFIG[REPOSITORY]}"` being `openjdk-jdk`, the `openjdk-jdk11u` repository fills out the criteria of that line, therefore `isValidGitRepo` is set to 0, and the src repository is attempted to be reset, causing the error.
Honestly, I have no idea why this has never been flagged before..

Proposed fix is to add a space after the repository variable, such as `..| grep "${BUILD_CONFIG[REPOSITORY]} "`
This means the repository _has_ to be `openjdk-jdk`, and `openjdk-jdk11` wouldn't work.
