### ISSUE TITLE
AdoptOpenJDK - Hangout 22/09/2017

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-build#171]
YouTube Stream: https://www.youtube.com/watch?v=iqCeHZXpNcE

Hangout's Link: https://hangouts.google.com/hangouts/_/fe443lfwobemphysp5y6lthchie

## Agenda

- Website UI redesign (found at https://staging.adoptopenjdk.net/)
- Wikipedia Submission https://en.wikipedia.org/wiki/Draft:AdoptOpenJDK
- Docker multi platform support https://github.com/AdoptOpenJDK/openjdk-docker
- Java Version Manager https://github.com/shyiko/jabba
- Google Brand Account  (AdoptOpenJDK)
- Twitter https://twitter.com/adoptopenjdk Add tweetdeck?
- TSC Formation https://github.com/AdoptOpenJDK/tsc
- Cleanup OpenJDK9 binaries https://github.com/AdoptOpenJDK/openjdk-build/issues/167
- JCK tests

**Comment by karianna** [comment]
**Rough meeting notes**

**Website**

Discussed latest website PR #190 

1.  Merge "Prebuilt OpenJDK Binaries" with "What type of user"
1. Remove "Java™ is the world's leading programming language and platform. The code for Java is open source and available at OpenJDK™. AdoptOpenJDK provides prebuilt OpenJDK binaries from a fully open source set of build scripts and infrastructure."
1. Combine 2 titles and remove 3 lines of text
1. 2nd set of icons to be smaller
1. Give end users JREs instead of JDKs
1. Change descriptive text of user type to tooltip
1. Martijn to change wording after first PR goes in
1. Discuss developer subtypes offline on slack
1. Put API link under / with Power user

** Wikipedia page **

1. Martijn to help add references with George

** Twitter **

1. George has almost got us verified

** Google+ / YouTube **

1. George has made the AdoptOpenJDK brand so we can host hangouts on air

**TSC**

Discussion to start electing TSC board

** OpenJDK 9 binaries **

Mani will update scripts to clean up JDK 9 builds

** Testing **

* Need to get the X11 server issue merged / fixed - Mani to grab
* Security tests as well - Mani to grab

**Comment by neomatrix369** [comment]
To build JREs look at this folder in every of the OpenJDK builds - https://ci.adoptopenjdk.net/job/[os-arch-platform-folder]/ws/openjdk/build/[os-arch-platform-folder]-normal-server-release/images/jre/

**Comment by neomatrix369** [comment]
Wrt to the design changes, please also look at the https://adoptopenjdk.net/getinvolved.html, to decide if the right types of audience has been targeted, I think we would need to sync the two pages (front and this page).

**Comment by neomatrix369** [comment]
#167 has now been addressed via PR [#172](https://github.com/AdoptOpenJDK/openjdk-build/pull/172).

**Comment by dsciarrino** [comment]
Closing as all issues have been resolved.
