### ISSUE TITLE
jdk8u-solaris-x64-hotspot failing to build

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-build#1722]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-hotspot/. Only seen on `build-siteox-solaris10u9-x64-1`, not sure if it affects other machines
```
Compiling ../generated/adfiles/ad_x86_64.cpp
"/export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace/build/src/hotspot/src/share/vm/runtime/thread.hpp", line 202: Warning: Identifier expected instead of "}".
1 Warning(s) detected.
gmake[6]: *** [/export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace/build/src/hotspot/make/solaris/makefiles/rules.make:143: accessFlags.o] Error 2
gmake[6]: *** Waiting for unfinished jobs....
"/export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace/build/src/hotspot/src/share/vm/runtime/thread.hpp", line 202: Warning: Identifier expected instead of "}".
1 Warning(s) detected.
gmake[6]: *** [/export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace/build/src/hotspot/make/solaris/makefiles/rules.make:143: abstractCompiler.o] Error 2
"/export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace/build/src/hotspot/src/share/vm/runtime/thread.hpp", line 202: Warning: Identifier expected instead of "}".
1 Warning(s) detected.
gmake[6]: *** [/export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace/build/src/hotspot/make/solaris/makefiles/rules.make:143: ad_x86_64.o] Error 2
gmake[5]: *** [/export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace/build/src/hotspot/make/solaris/makefiles/top.make:112: the_vm] Error 2
gmake[4]: *** [/export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace/build/src/hotspot/make/solaris/Makefile:226: product] Error 2
gmake[3]: *** [Makefile:231: generic_build2] Error 2
gmake[2]: *** [Makefile:177: product] Error 2
gmake[1]: *** [HotspotWrapper.gmk:45: /export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace/build/src/build/solaris-x86_64-normal-server-release/hotspot/_hotspot.timestamp] Error 2
gmake: *** [/export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace/build/src//make/Main.gmk:110: hotspot-only] Error 2
```

**Comment by M-Davies** [comment]
Looks like this is fixed now (16/06/2020)

**Comment by sxa** [comment]
Started working in https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-hotspot/341 after failing up to https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-hotspot/340.

I had initially wondered if it was related to our new workspace cleaning logic (https://github.com/AdoptOpenJDK/openjdk-build/commit/e279fe73cc25fc233ad86aaa9afcadcb3bb41e6b and https://github.com/AdoptOpenJDK/openjdk-build/commit/5a84d61d3e821b45d3750130bcb4cbaa554dd4be) but they went in on the 10th (six days before it started working)

**Comment by preethis00-hclt** [comment]
Compiling jdk8u directly from http://hg.openjdk.java.net/jdk8u/jdk8u/ in Solaris 11 x86. Am getting the same error :
Compiling /export/home/preethi/openjdk8u/hotspot/src/share/vm/compiler/abstractCompiler.cpp
Compiling /export/home/preethi/openjdk8u/hotspot/src/share/vm/utilities/accessFlags.cpp
Compiling ../generated/adfiles/ad_x86_32.cpp
"/export/home/preethi/openjdk8u/hotspot/src/share/vm/runtime/thread.hpp", line 202: Warning: Identifier expected instead of "}".
1 Warning(s) detected.
gmake[6]: *** [/export/home/preethi/openjdk8u/hotspot/make/solaris/makefiles/rules.make:148: accessFlags.o] Error 2
gmake[6]: *** Waiting for unfinished jobs....
"/export/home/preethi/openjdk8u/hotspot/src/share/vm/runtime/thread.hpp", line 202: Warning: Identifier expected instead of "}".
1 Warning(s) detected.
gmake[6]: *** [/export/home/preethi/openjdk8u/hotspot/make/solaris/makefiles/rules.make:148: abstractCompiler.o] Error 2
"/export/home/preethi/openjdk8u/hotspot/src/share/vm/runtime/thread.hpp", line 202: Warning: Identifier expected instead of "}".
1 Warning(s) detected.
gmake[6]: *** [/export/home/preethi/openjdk8u/hotspot/make/solaris/makefiles/rules.make:148: ad_x86_32.o] Error 2
gmake[5]: *** [/export/home/preethi/openjdk8u/hotspot/make/solaris/makefiles/top.make:112: the_vm] Error 2
gmake[4]: *** [/export/home/preethi/openjdk8u/hotspot/make/solaris/Makefile:226: product] Error 2
gmake[3]: *** [Makefile:231: generic_build2] Error 2
gmake[2]: *** [Makefile:177: product] Error 2
gmake[1]: *** [HotspotWrapper.gmk:45: /export/home/preethi/openjdk8u/build/solaris-x86-normal-server-release/hotspot/_hotspot.timestamp] Error 2
gmake: *** [/export/home/preethi/openjdk8u//make/Main.gmk:110: hotspot-only] Error 2

What code changes made to fix this issue. Can you please suggest.
