### ISSUE TITLE
jdknext windows build break: 05:36:06  Failed test: hudson.AbortException: Environment variable JAVA_FEATURE_VERSION not set

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#1820]
**Platform:** jdk-windows-x64-openj9

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-openj9/3/console

**Comment by M-Davies** [comment]
Caused by https://github.com/AdoptOpenJDK/openjdk-build/pull/1574. 

Seems like it's something wrong with [this line](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/make-adopt-build-farm.sh#L27)

**Comment by M-Davies** [comment]
That line is ok after local testing and it [this line can be seen in the output](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/make-adopt-build-farm.sh#L52) so that means the groovy script can't see variables created in `make-adopt-build-farm.sh`. I'll have a look to see if there any variables set in jenkins that we can compare against instead

FYI @ShishirH

**Comment by M-Davies** [comment]
Reverting the problem commit for now since it's a build break https://github.com/AdoptOpenJDK/openjdk-build/pull/1821
