### ISSUE TITLE
OpenJ9 boot jdk issue is not resolved 

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-build#1907]
**Platform:**
jdk-linux-aarch64-openj9
jdk-linux-ppc64le-openj9
** jdk-linux-x64-openj9**
** jdk-windows-x64-openj9**

**Architecture:**

Please describe the issue that you are having with our binaries and if possible how to recreate it.

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-aarch64-openj9/27/consoleFull

`05:14:22 Running ddrgen to generate j9ddr.dat and superset.dat 05:15:51 Blob written to file: ../j9ddr.dat 05:15:51 Superset written to file: ../superset.dat 05:15:51 gmake[4]: Leaving directory '/home/jenkins/workspace/build-scripts/jobs/jdk/jdk-linux-aarch64-openj9/workspace/build/src/build/linux-aarch64-server-release/vm/ddr' 05:15:51 05:15:51 ERROR: Build failed for targets 'product-images legacy-jre-image test-image debug-image' in configuration 'linux-aarch64-server-release' (exit code 2) 05:15:51
`
Issue tackled in PR : #1890

after talking to @M-Davies ,It looks like it isn’t using an OpenJ9 boot jdk.

```
05:07:29  Tools summary:
05:07:29  * Boot JDK:       openjdk version "15" 2020-09-15 OpenJDK Runtime Environment AdoptOpenJDK (build 15+27-202006170324) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15+27-202006170324, mixed mode, sharing)  (at /usr/lib/jvm/jdk-15+27)
05:07:29  * Toolchain:      gcc (GNU Compiler Collection)
05:07:29  * C Compiler:     Version 7.5.0 (at /usr/local/gcc/bin/gcc-7.5)
05:07:29  * C++ Compiler:   Version 7.5.0 (at /usr/local/gcc/bin/g++-7.5)
```

**Comment by M-Davies** [comment]
The problem here is that the [initial change](https://github.com/AdoptOpenJDK/openjdk-build/issues/1890) only sets an openj9 boot jdk on machines that don't have a valid boot jdk installed. The [change](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/platform-specific-configurations/linux.sh#L100) isn't used for instances where we [don't have to download a boot jdk](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/platform-specific-configurations/linux.sh#L91-L96). We would need to alter the [inital setting of the boot jdk](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/make-adopt-build-farm.sh#L81-L102) to cover this weakness too

**Comment by sxa** [comment]
We've disabled the use of the installed book JDKs for now, but should look at re-enabling it later once OpenJ9 have the symbols defined in order to avoid having to have two boot JDKs of each level on the build machines.
