### ISSUE TITLE
Corretto builds failing with Json error

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#1954]
Looks like na issue in our Json and not something in the codebase
```
[Pipeline] // node
[Pipeline] End of Pipeline
groovy.json.JsonException: expecting '}' or ',' but got current char '"' with an int value of 34

The current character read is '"' with an int value of 34
expecting '}' or ',' but got current char '"' with an int value of 34
line number 25
index number 605
    "CLEAN_WORKSPACE": true
....^
```

**Comment by M-Davies** [comment]
The reported [failing build](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-corretto/157/) is a manual one kicked off by @sxa without a host pipeline. It's not part of the nightly builds.

The cause was due there not being a comma after the `ENABLE_TESTS` value in the parameters:
```
    ...
    "ENABLE_TESTS": false
    "CLEAN_WORKSPACE": true
}
```
A new corretto build has been kicked off to replace the reported error https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-corretto/158/console
