### ISSUE TITLE
Latest nightly for 8u262 does not include latest patches from jdk8u master mercurial repo

### ISSUE THREAD

**Issue by jpbempel** [AdoptOpenJDK/openjdk-build#1958]
**Platform:**
linux

**Architecture:**
x64

We have tried the latest nightly build for 8u262 but it seems it missing some recent patches that are merged into 8u master (see https://hg.openjdk.java.net/jdk8u/jdk8u/hotspot/, specially JDK-8245167). There is no trace of those in https://github.com/AdoptOpenJDK/openjdk-jdk8u

Thanks

**Comment by sxa** [comment]
Looks like https://ci.adoptopenjdk.net/job/git-mirrors/job/git-hg-jdk8u/ has been failing recently (errors in the log but they're not causing the job overall to show as failing. Last update to the jdk8u mirror was 26 days ago so we're probably missing quite a few changes

**Comment by sxa** [comment]
@karianna This looks to have been failing since the day you moved jenkins jobs into `git-mirrors` (Last merge into the repo was 26 days ago and we were discussing that in Slack on June 12th)

I can try cleaning out the workspace so it repopulates from scratch on the machine but if this started failing as the result of using a clean directory on the machine I'm not optimistic it will resolve it.

**Comment by sxa** [comment]
Oh hang on ... I think the mirror may not initialise a repo automatically - Will do a re-init ... But this situation needs to be trapped (and possibly have inits done automatically where there isn't one in place...)

**Comment by karianna** [comment]
OK I'll look with George tomorrow - I thought we'd caught all of these.

**Comment by andrew-m-leonard** [comment]
Fixed by PR : https://github.com/AdoptOpenJDK/openjdk-build/pull/1961
and doing a local repo re-build
Local repo re-build was failing due to chmod +x git working change from script
