### ISSUE TITLE
debug symbols are deleted during build despite of setting --with-native-debug-symbols=external

### ISSUE THREAD

**Issue by jennli** [AdoptOpenJDK/openjdk-build#1972]
impacting all `hotspot` builds.

when `--with-native-debug-symbols=external` flag is passed to configure, I expect the subsequent build will output all the debug symbol files. However, I am not getting any debug symbols due to the following lines explicitly removing them:

```bash
 # .diz files may be present on any platform
  # Note that on AIX, find does not support the '-delete' option.
  find "${jdkTargetPath}" "${jreTargetPath}" -type f -name "*.diz" | xargs rm -f || true

  case "${BUILD_CONFIG[OS_KERNEL_NAME]}" in
    *cygwin*)
      # on Windows, we want to remove .map and .pdb files
      find "${jdkTargetPath}" "${jreTargetPath}" -type f -name "*.map" -delete || true
      find "${jdkTargetPath}" "${jreTargetPath}" -type f -name "*.pdb" -delete || true
      ;;
    darwin)
      # on MacOSX, we want to remove .dSYM folders
      find "${jdkTargetPath}" "${jreTargetPath}" -type d -name "*.dSYM" | xargs -I "{}" rm -rf "{}"
      ;;
    *)
      # on other platforms, we want to remove .debuginfo files
      find "${jdkTargetPath}" "${jreTargetPath}" -type f -name "*.debuginfo" | xargs rm -f || true
      ;;
  esac
```
https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L623-L641

I feel this can be replaced with setting `--with-native-debug-symbols=none`. But the following line seems to indicate that there was a use case for OpenJ9 to delete all the debug symbol files while skipping the `--with-native-debug-symbols=none` flag.
https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L291

 I'd like to bring up this question and figure out if we can have a better approach here, since setting that flag to `none` should just remove the debug symbols from the output.

**Comment by sxa** [comment]
@keithc-ca From memory the debug symbol changes were yours - can you take a look?

**Comment by keithc-ca** [comment]
Yes, I recently made changes to the code that removes debug files, but the practice of deleting them precedes my involvement in that area. In fact, I remember being surprised it was happening (at first) because it was removing the files that OpenJ9 wanted to be in debug images.

I believe the configure option `--with-native-debug-symbols=external` is actually the default on most platforms. However, most people downloading a JDK (and more so for those downloading a JRE) won't want those extra files, so I can see why the code to remove them was added.

OpenJ9 explicitly does want those files in debug images (and there is no option to control the production of the debug information for openj9-specific binaries), so OpenJ9 is happy with the current state of affairs.

I suggest that what is wanted is a way to capture the debug information (if any) produced in hotspot builds, and packaged as a debug image like is done for OpenJ9. Then users can choose to download the JDK and optionally the debug image. I expect [DebugImage.gmk](https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/closed/DebugImage.gmk) should work as-is (or with very few modifications) for hotspot builds as well. It should be as simple as adding a target to `Main.gmk` to invoke `DebugImage.gmk`:
```
debug-image : exploded-image
	+$(MAKE) -f $(TOPDIR)/closed/DebugImage.gmk SPEC=$(SPEC)
```

**Comment by jennli** [comment]
with this line https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L291 
I think it is setting `--with-native-debug-symbols=none`, which should be picked up by `configure` unless we explicitly pass in that argument with `external`, so I'm curious why there is still a need of removing debug symbols.

**Comment by jennli** [comment]
fixed by https://github.com/AdoptOpenJDK/openjdk-build/pull/2008
Thank you!
