### ISSUE TITLE
Request to run sanity and extended.functional testing to nightly builds of Aarch64

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#2085]
The OpenJ9 project doesn't have enough Aarch64 machines to provide test coverage for this platform. Adopt is running a number of test suites on this platform already, but not the sanity.functional and extended.functional suites. This is a request to add these test buckets to the nightly builds.

**Comment by llxia** [comment]
@LongyuZhang could you help with this issue? Thanks.
This can be done after PR https://github.com/AdoptOpenJDK/openjdk-build/pull/2024 is merged.

**Comment by smlambert** [comment]
Yes, I have generated these test jobs and run them in the past, but not included yet to be launched as part of the nightly test targets.  It will be definitely better to launch them from here (instead of via Jenkins cron) as then we will be able to see the results in TRSS, since it is monitoring these build pipelines.

**Comment by llxia** [comment]
@pshipton @smlambert should we enable aarch64 testing for JDK8 and JDK11? Do we want to enable for JDK16? We have [8 aarch64 testing machines](https://ci.adoptopenjdk.net/label/ci.role.test&&sw.os.linux&&hw.arch.aarch64/) at Adopt. Since we run other tests on aarch64 as well, maybe we should enable functional testing on one or two JDK versions and adjust this as needed.

**Comment by pshipton** [comment]
I understand the aarch64 resource is concentrating on jdk11 followed by jdk8. I don't think much effort has been made to fix jdk15 issues, and in the end we didn't include aarch64 in the last jdk15 release. jdk16 is WIP and could have issues unrelated to aarch64 at this point. I'd start with jdk11, add jdk8 if machine resources allow, and we can look at adding jdk15 or jdk16 later.

@knn-k fyi.

**Comment by pshipton** [comment]
Noticed that in the 0.23.0 M2 build there is a mismatch between test material and build. It's running the head stream tests against the 0.23.0 release content.

https://trss.adoptopenjdk.net/resultSummary?parentId=5f7b58b111d26031c1db12b7

**Comment by llxia** [comment]
This is not specific to aarch64. This is a general issue. It shows up in aarch64 because we enabled functional tests on aarch64.

The default OPENJ9_BRANCH is set to `master` unless it is overridden by the upstream build script. In this case, it should be set to `v0.23.0-release`. 

I manually trigger the test build with `v0.23.0-release` branch. However, the upstream SDK does not exist anymore
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_extended.functional_aarch64_linux/11/

To fix this, the upstream build script should allow the user to set OPENJ9_BRANCH. Similar to `RELEASE_TAG`

**Comment by smlambert** [comment]
I believe this can be closed since https://github.com/AdoptOpenJDK/openjdk-build/pull/2105 was merged and https://github.com/AdoptOpenJDK/openjdk-build/pull/2166 to address the version skew.

**Comment by pshipton** [comment]
@smlambert I believe the functionality tests are only running for jdk11. If there is machine capacity, should I open another issue to run them for jdk8?

**Comment by smlambert** [comment]
Re-open to add for jdk8

**Comment by M-Davies** [comment]
[JDK/aarch64/J9 sanity.functional testing](https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk8_j9_sanity.functional_aarch64_linux/) and [JDK/aarch64/J9 extended.functional testing](https://ci.adoptopenjdk.net/view/Test_functional/job/Test_openjdk8_j9_extended.functional_aarch64_linux/) are both enabled in the nightly pipelines. Closing...
