### ISSUE TITLE
Add comments to build-scripts

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-build#2110]
Pretty self explanatory, we need comments on each function and/or sections of importance inside the [pipelines folder](https://github.com/AdoptOpenJDK/openjdk-build/tree/master/pipelines) to ease newcomers into the codebase.
- [Example of a function comment](https://github.com/AdoptOpenJDK/openjdk-build/blob/971b885dd7c558dde4f7f47f1e494defc7ff4d9a/pipelines/build/common/config_regeneration.groovy#L121-L126)
- [Example of a section of importance comment](https://github.com/AdoptOpenJDK/openjdk-build/blob/971b885dd7c558dde4f7f47f1e494defc7ff4d9a/pipelines/build/common/config_regeneration.groovy#L419)

**Comment by hendrikebbers** [comment]
@M-Davies I assume that this issue is to complexe for a good first issue. A newcomer has no idea about the functionality about that methods. But having such comments are really important to help newcomers to get into the project :) I would remove the 'good first issue - candidate" label for this issue.
