### ISSUE TITLE
Validate cmake builds of OpenJ9 on Windows

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#2126]
cmake support is enabled on most platforms now for OpenJ9 but not Windows (there is one final fix that's going in). We should attempt to run a cmake build to verify that our build systems are set up with a suitable working cmake.

Suggest running a build manually on the machine with cmake enabled as it is for other platforms (`--with-cmake` at configure time shold do it)

**Comment by Willsparker** [comment]
- [ ] build-softlayer-win2012r2-x64-1
- [ ] build-softlayer-win2012r2-x64-2
- [ ] build-azure-win2012r2-x64-1
- [ ] build-azure-win2012r2-x64-2

**Comment by Willsparker** [comment]
After installing `cmake` via Cygwin (admittedly version `3.14.5` ), as well as the non-cygwin version (see the [windows playbook](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cmake/tasks/main.yml) in infra), I've been unable to get a working version of `cmake` on the Softlayer machines - when running `cmake` via `cmd`, I get a popup saying `The procedure entry point uname_x could not be located in the dynamic link library C:\cygwin64\bin\cyguv-1.dll`, followed by a `cmake has stopped working error`. Installing `libcv-devel` didn't change anything, and `cyguv-1` doesn't appear in the Cygwin setup list.

Due to https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1594 , I don't think it's a priority to try and fix this, therefore I'm going to just focus on confirming `cmake` is okay on the new `IBMCloud` machines :-)

- [ ] build-ibmcloud-win2012r2-x64-1
- [ ] build-ibmcloud-win2012r2-x64-2

**Comment by Willsparker** [comment]
All Windows-build machines should be ready to build OpenJ9 w/ cmake now :+1:
