### ISSUE TITLE
Create production ready builds which align with Oracle Jan 2018 quarterly update

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-build#214]
On 16th Jan 2018 Oracle released the latest quarterly update.  This means the AdoptOpenJDK can create builds at the same code level (jdk8u162-b12) and make them available on the main download page.

openjdk-hotspot builds should be able to be created right away, openjdk8-openj9 cannot be built just yet as we are waiting for an official eclipse/openj9 release level to combine with the openjdk level.

Once created the builds should be tested (including the JCK), and then marked as 'production ready' (see https://github.com/AdoptOpenJDK/openjdk-website/issues/209).

**Comment by sxa555** [comment]
From @gdams Ref: https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1518523866000151 - I've already started working on part 1 of this:

1) we need to update makejdk.sh to be able to run on a specific tag that we define in a job
2) we need to update https://github.com/AdoptOpenJDK/openjdk-website-backend/blob/master/sbin/Release.sh#L39 to auto fetch the VERSION var so that we don't have to set it twice (allowing it to fall out of sync)

2 isn't perhaps necessary for an actual release because we are setting the release that we want to build against but it is an issue for nightly builds because it doesn't update automatically as new tags appear (causing the issue Martijn linked to)

**Comment by sxa555** [comment]
openj9 builds have been updated with the the quarterly release at HEAD and have been initiated at https://ci.adoptopenjdk.net/view/Pipelines/job/openjdk8_openj9_nightly_pipeline/ although xlinux is currently failing - see https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/44.

**Comment by sxa555** [comment]
I'm prototyping a tag option using the jdk10 arm32 builds (since we don't ship these as releases it seemed a safe option!) at https://ci.adoptopenjdk.net/job/openjdk10_build_arm32_linux/ 

The `--tag` option to `makejdk.sh` was added in https://github.com/AdoptOpenJDK/openjdk-build/pull/220

**Comment by sxa555** [comment]
Ref the OpenJ9 build - AIX build machine ran out of space - now fixed https://github.com/AdoptOpenJDK/openjdk-build/issues/222
xLinux build is failing https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/44
WIndows OpenJ9 has a known issue: http://github.com/eclipse/openj9/issues/845 (Start at http://github.com/eclipse/openj9/issues/845#issuecomment-363406782)

**Comment by sxa555** [comment]
Using the jdk10 arm32 builds wasn't the smart idea I thought it was as they appear to be fundamentally broken even without the tag parameter being specified. Have therefore integrated the option on the xlinux jdk10 build jobs instead ...

**Comment by sxa555** [comment]
`sbin/build.sh` will also need updated as it has it's own detection of the latest tag that it uses for the top level directory inside the tarball

**Comment by neomatrix369** [comment]
@sxa555 left some comments  - https://github.com/AdoptOpenJDK/openjdk-build/pull/220

**Comment by neomatrix369** [comment]
Archiving our conversation for posterity https://github.com/AdoptOpenJDK/openjdk-build/pull/220#discussion_r168516626

**Comment by sxa555** [comment]
openjdk-openj9 "Release Candidate" builds are these ones which I'll tell jenkins to save in the absence of us having an official RC process just now:
https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_ppc64_aix/77/artifact/OpenJDK8_ppc64_AIX_201822020500.tar.gz
https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_ppc64le_linux/74/artifact/OpenJDK8_ppc64le_Linux_201822021300.tar.gz
https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_s390x_linux/73/artifact/OpenJDK8_s390x_Linux_201822020800.tar.gz
xLinux: TBD

**Comment by sxa555** [comment]
OpenJ9 branch updated to `openj9-0.8` in https://github.com/AdoptOpenJDK/openjdk-build/commit/d0e331732423bcb8d9086975b7191dd4d04badb6
Builds were initially coming out on the nightly site still labelled on the web site as jdk8u152 but were actually 162 (as you can see inside the tarballs) I'm re-running the nightly pipeline to resolve that with the second build on March 1.
JCK runs are in progress

**Comment by lumpfish** [comment]
We now have the builds for the openjdk8-openj9 variant which maps to the Jan 18 oracle update. What is the status for the openjdk8-hotspot builds?

**Comment by sxa555** [comment]
I think I'm reasonably close to having a reasonable mirror in https://github.com/sxa555/openjdk8-temp but need to do some sanity checks first. Also I haven't done anything to mimic the `dev` branch we build from. I've been test building it from various tags at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/sxa_openjdk8_xlinux/.

I've attempted to get mirrors of all tags from `8u144` up to the latest `8u172` - only taking the latest `-b` revision of each one since those correspond to the GA levels.

**Comment by sxa555** [comment]
Hopefully this update makes sense - I'm in a bit of a daze today ...

So https://github.com/sxa555/openjdk8-temp now finally has (I believe!) the same HEAD as https://github.com/AdoptOpenJDK/openjdk-jdk8u (other than it missing `get_source.sh` and `README` but crucially includes the tags for earlier builds.

The questions outstanding now to produce production read HotSpot buids are:

1. Can someone else give me a sanity check on the codebase to see if it looks sane. That repo was populated using a modified - and still a little "fluid" - version of the script currently sitting on my laptop that is used to populate the OpenJDK+Eclipse OpenJ9 repository under http://github.com/ibmruntimes
2. We'll need to get this new script in place to populate the repository at adoptopenjdk once we'rte happy it's done the right thing (Obviously, under sxa555 is not the sane place for this) - if we have to remirror this could take a couple of days (machine time)
3. I have no real idea of what we have in the `dev` branch (the one we build from) or how to populate it so that will be a prereq to the following steps
4. Build from the `jdk8u162-b12` tag (or will it need an equivalent on the `dev` branch?)
5. Run all the tests against it
6. Ship it! (Subject to the tests not indicating a problem, obvs!)

While I admit the chances of getting all that done before the next quarterly Oracle release comes out is fairly slim, it gives us something to work towards and streamline for next time round ;-)

FYA @neomatrix369 @karianna @lumpfish @gdams @irinarada (feel free to assign yourself to this item along with me if you so wish, but I suspect tagging you is enough to get it on your notifications list now)

**Comment by karianna** [comment]
Hi @sxa555 

1.) It looks sane and you can probably check using a git or local linux diff tool between your repo and openjdk-jdk8u (dev branch)

2.) I'm not sure which new script you are referring to here?

3.) The dev branch is almost identical to master except it contains the 1-2 patches we added for supporting some platforms that OpenJDK upstream refused the patches for.  I'd suggest running a diff between dev and master which should give you what those small patches are...

4.) Yes build from the tag on the dev branch

5.) & 6.) :-)

7.) Profit!  err wait...

**Comment by sxa555** [comment]
1) Yep it seemed ok to me from diffing the directores other than the couple of other files mentioned
2) It's one that I got from @yongja79 (I think that's his ID) and I don't think it's on github anywhere, but had support for doing clever stuff with `git filter-branch` to mirror the tags accurately. It might have been based on the adoptopenjdk one. I've tweaked it a bit to mirror a fixed set of historic tags (The last one for each `u` level which means it just gets the GA ones. Obviously if we're happy with this I'll chuck it back up into the repo :-)
3+4) My only concern with the patches is how we handle the tags. Should the tags in the master branch or the dev branch have the quarterly level. Possibly master, with a suffix `-ao` or something for the equivalents in `dev`. Will need some work to get such tags in the dev branch set up.
5,6,7) Ker-ching! (Hahahaahaaahahahaa)

**Comment by karianna** [comment]
I thought the hg-git scripts pulled in the tags for both master and dev?  If not that's perhaps where we should fix that.

**Comment by sxa555** [comment]
It put tags in but they weren't correct - didn't seem to be taking in account all the subrepos so they weren't all there when you checked out the tag. I'll look into it again if there's stuff to deal with the `dev` branch too there already though.

**Comment by lumpfish** [comment]
openjdk9-openj9 builds aligning with the Jan18 were created and tested, but the issues around building the correct level of openjdk8-hotspot were still ongoing at the time of the Oracle Apr 2018 quarterly update.
The build issues would now be better continued by building the new update level.
See https://github.com/AdoptOpenJDK/openjdk-build/issues/303 and https://github.com/AdoptOpenJDK/openjdk-build/issues/304.

**Comment by sxa555** [comment]
I'm going to close this as we will not be completing a release of the Jan 18 quarterly update as it has been superceded by the April releases which we have done under https://github.com/AdoptOpenJDK/openjdk-build/issues/303
