### ISSUE TITLE
jdk8 nightly builds using --with-milestone=fcs as if a Release

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2188]
Nightly builds are now using --with-milestone=fcs which means the java --version output and version string are "Release" type format and not "internal" like they used to be

**Comment by karianna** [comment]
Possibly related to https://github.com/AdoptOpenJDK/openjdk-build/pull/2186/

@M-Davies ?

**Comment by M-Davies** [comment]
Slightly related, albeit --with-milestone=fcs has been in jdk8 build.sh [for a while now, possibly since the beginning of time](https://github.com/AdoptOpenJDK/openjdk-build/search?q=--with-milestone%3Dfcs&type=commits)

https://github.com/AdoptOpenJDK/openjdk-build/blob/79c98cee0c3ba23b8ac2864d71a11b32bbf33ed2/sbin/build.sh#L176-L179
@andrew-m-leonard What would be the correct config ag (if any) that would replace fcs?

**Comment by andrew-m-leonard** [comment]
@M-Davies basically --with-milestone=fcs should only be for release builds, Nightlies should not specify it

**Comment by andrew-m-leonard** [comment]
@M-Davies one aspect to consider is if anyone doing Release pipelines has been used to not specifying --with-milestone=fcs, would then now need to specify it (as per RELEASING.md), unless the release pipeline could automatically add it?

**Comment by M-Davies** [comment]
> @M-Davies one aspect to consider is if anyone doing Release pipelines has been used to not specifying --with-milestone=fcs, would then now need to specify it (as per RELEASING.md), unless the release pipeline could automatically add it? i.e.if type="Release"

I'll add it as a default in the shell scripts in a draft PR (since there isn't currently a way to pass config args based on releases).
