### ISSUE TITLE
JVM Crash

### ISSUE THREAD

**Issue by LloydChristmasIII** [AdoptOpenJDK/openjdk-build#2419]
**What are you trying to do?** Play a game on linux that runs java

**Expected behaviour:** i open the software and it will load for awhile and then just randomly crash

**Observed behaviour:**i open the software and it will load for awhile and then just randomly crash

**Any other comments:** I checked my logs and found this 
[jvm_crash_pid_8564.log](https://github.com/AdoptOpenJDK/openjdk-build/files/5889629/jvm_crash_pid_8564.log)

**Comment by aahlenst** [comment]
Thanks for getting in touch, but the problem isn't Java, The crash is in `i965_dri.so` which seems to be some driver. Maybe the OpenGL wrapper on top of it feeds it some bad pointers. Anyhow: Try on another machine, with another Linux distribution, or contact the vendor of the game. It's hard to say what the best course of action is because I have nothing but the crash dump.
