### ISSUE TITLE
Changesets imported from mercurial has an invalid email field(devnull@localhost)

### ISSUE THREAD

**Issue by ararunprasad** [AdoptOpenJDK/openjdk-build#270]
Changesets imported from mercurial to git has an invalid email field, PSB,

commit e8daa3be8be382c709918152fb15ff93d87e8bff
Author: kcr <devnull@localhost>
Date:   Tue Mar 20 13:01:33 2018 -0700

    8198654: Switch FX's default GTK version to 3
    Reviewed-by: prr
It would be better to remove the invalid email address(devnull@localhost) for futures merges.

Refer https://github.com/javafxports/openjdk-jfx/issues/31

**Comment by karianna** [comment]
Is this for the OpenJFK port?

**Comment by ararunprasad** [comment]
@karianna yes.

**Comment by tiainen** [comment]
As mentioned by @ararunprasad , this issue was originally created in the OpenJFX port. Since we use the scripts from this repository, I thought it would make sense to create the issue in this repository instead. The mirror repositories for OpenJDK that are maintained by the AdoptOpenJDK github account are affected as well.

**Comment by karianna** [comment]
See #238
