### ISSUE TITLE
Builds for MacOS are not recognized by Java Tools

### ISSUE THREAD

**Issue by mbidewell** [AdoptOpenJDK/openjdk-build#321]
If I follow the instructions for installing AdoptOpenJDK builds on MacOS, I get a functioning command line, however /usr/libexec/java_home does not recognize the install (Even if placed into /Library/Java/JavaVirtualMachines) due to the directory structure and lack of an Info.plist file.  The Java 10 build from http://jdk.java.net/10/ contains the correct information, however builds from adoptopenjdk do not.  IDEs such as Eclipse and Intelij also do not recognize the AdoptOpenJDK binaries.

This makes adoptopenjdk unsuable on MacOS for all practical purposes.

**Comment by gdams** [comment]
This is the file structure that macOS expects:

```tree
➜  jdk1.8.0_121.jdk tree -v -L 3 --charset utf-8
.
└── Contents
    ├── Home
    │   ├── ASSEMBLY_EXCEPTION
    │   ├── COPYRIGHT
    │   ├── LICENSE
    │   ├── README.html
    │   ├── THIRDPARTYLICENSEREADME-JAVAFX.txt
    │   ├── THIRDPARTYLICENSEREADME.txt
    │   ├── THIRD_PARTY_README
    │   ├── bin
    │   ├── db
    │   ├── demo
    │   ├── include
    │   ├── javafx-src.zip
    │   ├── jre
    │   ├── lib
    │   ├── man
    │   ├── release
    │   ├── sample
    │   └── src.zip
    ├── Info.plist
    └── MacOS
        └── libjli.dylib -> ../Home/jre/lib/jli/libjli.dylib

11 directories, 12 files
```

**Comment by karianna** [comment]
This may be one for the installer project, but lets see.

**Comment by dougxc** [comment]
When building the JVMCI JDKs available at http://www.oracle.com/technetwork/oracle-labs/program-languages/downloads/index.html, we preserve the `Contents/Home` prefix for the macOS build for precisely the reasons started in this issue.
```
> tree -L 3 /Library/Java/JavaVirtualMachines/labsjdk1.8.0_172-jvmci-0.44
/Library/Java/JavaVirtualMachines/labsjdk1.8.0_172-jvmci-0.44
└── Contents
    ├── Home
    │   ├── COPYRIGHT
    │   ├── LICENSE
    │   ├── README.html
    │   ├── THIRDPARTYLICENSEREADME-JAVAFX.txt
    │   ├── THIRDPARTYLICENSEREADME.txt
    │   ├── bin
    │   ├── db
    │   ├── include
    │   ├── javafx-src.zip
    │   ├── jre
    │   ├── lib
    │   ├── man
    │   ├── release
    │   └── src.zip
    ├── Info.plist
    └── MacOS
        └── libjli.dylib -> ../Home/jre/lib/jli/libjli.dylib

9 directories, 10 files
```

**Comment by karianna** [comment]
@johnoliver Since you're successfully building via the new build scripts - are you able to take a look at this one?

**Comment by gdams** [comment]
@karianna I really don't feel that our builds should be churning out the binaries in the stucture! We should probably make this part of the installer for MacOS so that it has the correct structure but our tarballs should remain the same IMO.

**Comment by karianna** [comment]
Yeah I'm not sure if the installer or the build produces the right structure though...

**Comment by gdams** [comment]
the build doesn't (and I don't think it should) the installer can be configured to produce this structure though

**Comment by lenborje** [comment]
I don't know if I point out something everybody already knows, but anyway...

When I build the JDK on my Mac, `make images` builds the requisite MacOS-friendly directory tree under `build/macosx-x86_64-normal-server-release/images/jdk-bundle/jdk-11.jdk/', in addition to the "standard linux tree" under `build/macosx-x86_64-normal-server-release/images/jdk/`.

```
$ tree -L 3 build/macosx-x86_64-normal-server-release/images/jdk-bundle/jdk-11.jdk
build/macosx-x86_64-normal-server-release/images/jdk-bundle/jdk-11.jdk
└── Contents
    ├── Home
    │   ├── bin
    │   ├── conf
    │   ├── demo
    │   ├── include
    │   ├── jmods
    │   ├── legal
    │   ├── lib
    │   ├── man
    │   └── release
    ├── Info.plist
    └── MacOS
        └── libjli.dylib -> ../Home/lib/jli/libjli.dylib
$ tree -L 1 build/macosx-x86_64-normal-server-release/images/jdk
build/macosx-x86_64-normal-server-release/images/jdk
├── bin
├── conf
├── demo
├── include
├── jmods
├── legal
├── lib
├── man
└── release

```

So it seems to that a "correct" MacOS installation archive could be created by simply selecting other source directory when creating it.

**Comment by breun** [comment]
I'm the maintainer of the OpenJDK ports in MacPorts. I'm currently using Oracle's OpenJDK builds, but I'm considering AdoptOpenJDK's builds.

I think it would be great if the AdoptOpenJDK releases for macOS would be ready to go when unpacked under `/Library/Java/JavaVirtualMachines`, just like the Oracle OpenJDK builds, because otherwise MacPorts would have to duplicate the stuff the installer does in order to construct the directory structure expected by these macOS tools.

**Comment by karianna** [comment]
Also, see https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/9

**Comment by planetf1** [comment]
I think the last point is salient ... The oracle jdk install will copy itself into that directory. The user needs to do nothing else to 'just use' the JDK. 

On docs... many don't read the docs, so at a minimum a warning or info in the actual install or otherwise very obvious would help if this isn't automated.

Also as a software engineer building java apps I need to work with multiple jdks, so I like the fact it isn't installed by default. I use 'jenv' to manage on macOS. It was just the current packaging seems caught between these two approaches. Of note also is that some commercial apps will fail with new versions of JDKs, so updating the 'default' version even as a novice user can be problematic

**Comment by breun** [comment]
I believe the original issue is fixed with the current AdoptOpenJDK 8u192 and 11.0.1 releases for macOS.
