### ISSUE TITLE
build-scaleway-x64-ubuntu-16-04-2 doesn't have JDK7_BOOT_DIR

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#347]
Causing failures of e.g. https://ci.adoptopenjdk.net/job/openjdk10_sap_build_x86-64_linux/ when run on that machine.

**Comment by karianna** [comment]
This is usually set on the jenkins node itself, do you have permission to set those?

**Comment by gdams** [comment]
This isn't meant to be a build machine. I'm not sure why it has the build label. It is the docker machine with no build deps installed. I'm removing the build label now.

**Comment by karianna** [comment]
OK, I'll revert my change of setting that boot dir.  I'll let you close this when you've made the label change.

**Comment by sxa555** [comment]
Should we consider renaming the host so it doesn't have build in the name too? That could lead people to re-add the tag

**Comment by gdams** [comment]
at some point I was thinking of creating a `docker` group of machines but hadn't got around to doing that yet

**Comment by smlambert** [comment]
If you are creating a docker group of machines please let me know... I have opened this https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/347 to get it installed on as many test machines as possible, since we will continue to extend our container-based testing.  (tests look for machines labelled sw.tool.docker - which I added to test machines where docker is installed).
