### ISSUE TITLE
Simplify mechanism for adjusting flags for openj9 release builds

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#431]
Currently involves manually modifying the individual bulid jobs to add in the extra parameters

**Comment by karianna** [comment]
Is this true with the new build scripts as well?  I think it's still a parameter to be passed in...

**Comment by johnoliver** [comment]
It is better in that it is checked in to source control rather than modifying the job in jenkins.

However the configuration of every combination of arch+os+impl can still be very unique so it is still not fantastic in that you end up with code like: 

https://github.com/johnoliver/openjdk-build/blob/overhaul-build-scripts-6/build-farm/platform-specific-configurations/linux.sh#L39

Where you are effectively special casing a narrow number of builds and applying a configuration.

So imo its better in that its in source code not CI configuration, but not great in that all the builds have a lot of unique config.

**Comment by adamfarley** [comment]
@sxa - Should this issue be closed?

@johnoliver 's comment sounds like he's saying the situation is non-optimal, but that the unique config options are stored in the right place (source control), and should not be controlled by the job in jenkins.

One compromise option could be to identify the most common extra-parameter combinations, tweak them by platform if needed, and to pass build script flags that trigger the addition of the right config flags for that platform. That is, if you had specific flags in mind while raising this.

Thoughts?

**Comment by sxa** [comment]
I think this may be ok with the current pipelines so I'll close this for now unless I hit an issue with it again.
