### ISSUE TITLE
Remove dependency on ftp.acc.umu.se

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#441]
Ref: https://github.com/AdoptOpenJDK/openjdk-build/issues/416
We pull other dependencies from https://ci.adoptopenjdk.net/userContent/ and should probably put freetype there too since ftp.acc.umu.se is currently not accessible.

**Comment by gdams** [comment]
@sxa555 looking at https://ci.adoptopenjdk.net/userContent/ it contains `freetype.zip` and `freemarker-2.3.8.tar.gz` Can this be closed?

**Comment by sxa555** [comment]
I don't think either are beign actively obtained from there though

**Comment by M-Davies** [comment]
Looking at [prepareWorkspace.sh](https://github.com/AdoptOpenJDK/openjdk-build/blob/031a280f1e32143f3199a0705ee77a9791d69cf7/sbin/prepareWorkspace.sh#L294-L295), we seem to have accepted using `download.savannah.gnu.org` for getting our freetype distros. 

Since we no longer use `ftp.acc.umu.se`, can this be closed @sxa ?

**Comment by sxa** [comment]
Seems to have been done somewhere within https://github.com/AdoptOpenJDK/openjdk-build/pull/566  - this commit specifically
```
Author: John Oliver <johno@insightfullogic.com>
Date:   Wed Sep 26 15:09:45 2018 +0100

    Merge branch 'new_build_scripts' of https://github.com/AdoptOpenJDK/openjdk-build into merge-upstream-3

commit 9e78e0d63fc6c07715a767d5254423b7757116f0
```
We've also modified the freetype source after https://github.com/AdoptOpenJDK/openjdk-build/issues/1780

I'm happy to close this as the original description is no longer valid
