### ISSUE TITLE
JDK11 build failure on AIX (HotSpot and OpenJ9)

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#456]
Creating this to ensure it's on the adoptopenjdk radar - issue is related to the `sigaction` symbol and is documented more fully at https://github.com/eclipse/openj9/issues/2468

**Comment by keithc-ca** [comment]
It's not specific to jsig. OpenJDK started using xlc's `-qvisibility=hidden` option (except with xlc version 12.1), but without a change to `JNIEXPORT` so that the link option `-bexpall` doesn't do what is needed.

I have a working fix, but it involves changing one source file to workaround what appears to be an xlc bug.

**Comment by sxa555** [comment]
Full fix also required removing `-lpthread` from the configure options we specify in our jenkins jobs. Now working on OpenJ9 builds.

**Comment by karianna** [comment]
Is this fixed for OpenJ9 and Hotspot builds now?

**Comment by sxa555** [comment]
Not fully - there's a second error that is fixed in OpenJ9 [but not HotSpot](https://ci.adoptopenjdk.net/view/JDK11%20WIP/job/openjdk11_build_ppc64_aix/) - I've removed the `reported with upstream team` now as the upstream team was OpenJ9 who have fixed their side :-)
```
ERROR: Build failed for targets 'images test-image' in configuration 'aix-ppc64-normal-server-release' (exit code 2) 

=== Output from failing command(s) repeated here ===
* For target support_native_java.base_libjava_BUILD_LIBJAVA_link:
ld: 0711-224 WARNING: Duplicate symbol: .jio_snprintf
ld: 0711-224 WARNING: Duplicate symbol: jio_snprintf
ld: 0711-224 WARNING: Duplicate symbol: .jio_fprintf
ld: 0711-224 WARNING: Duplicate symbol: .isnan
ld: 0711-224 WARNING: Duplicate symbol: jio_fprintf
ld: 0711-344 See the loadmap file /ramdisk0/build/workspace/openjdk11_build_ppc64_aix/openjdk/build/aix-ppc64-normal-server-release/support/native/java.base/libjava/libjava.loadmap for more information.
ld: 0711-317 ERROR: Undefined symbol: .VerifyFixClassname
ld: 0711-317 ERROR: Undefined symbol: .VerifyClassname
ld: 0711-317 ERROR: Undefined symbol: .VerifyClass
ld: 0711-317 ERROR: Undefined symbol: .VerifyClassForMajorVersion
```
NOTE: I have created https://github.com/AdoptOpenJDK/openjdk-build/issues/461 to cover doing a check of our current configure flags.

**Comment by M-Davies** [comment]
This looks to be resolved now. @karianna can this be closed?

**Comment by karianna** [comment]
> This looks to be resolved now. @karianna can this be closed?

AIX Builds are green for Hotspot and JDK 11 so yes.
