### ISSUE TITLE
Compile OpenJ9 for Linux on ppc64le on Rhel/Cent 7

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-build#579]
Currently the builds are compiling OpenJ9 on Linux ppc64le on Ubuntu16 ([build-osuosl-ubuntu1604-ppc64le-1](https://ci.adoptopenjdk.net/computer/build-osuosl-ubuntu1604-ppc64le-1/))

I believe the Adopt Ubuntu 16 ppc64le machine has a newer glibc version than rhel/cent7. When I try and run these SDKs on a Centos 7 machine I get the error
```glibc_2.22 not found```

https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11/job/jdk11-linux-ppc64le-openj9/
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk10u/job/jdk10u-linux-ppc64le-openj9/
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-ppc64le-openj9/

Adopt also has Cent7 ppc64le machines
https://ci.adoptopenjdk.net/label/ppc64le&&centos7/
These should have a lower glibc version.

Perhaps this work was blocked due to ibmruntimes/openj9-openjdk-jdk8#7. I believe this is resolved with make 4.1 as @sxa555 suggests.

**Comment by sxa555** [comment]
@AdamBrousseau I am going to close this as a dup of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/256 - as per the PR you've seen (which only appears to affect 10/11 because they were the only ones explicitly locked to Ubuntu) this should now be enough - I did some builds yesterday on our Centos/ppc64le machines and they looked ok, so now that the PR is merged my plan is to remove the `build` tags from the Ubuntu build machines so everything will be on CentOS7 now.
