### ISSUE TITLE
Strange letter "U" in ZIP filename

### ISSUE THREAD

**Issue by alexhass** [AdoptOpenJDK/openjdk-build#674]
`OpenJDK8U-jdk_x64_windows_hotspot_8u181b13`

No idea what the "U" after "OpenJDK8" should mean.

And after it is extracted the folder is now named `jdk8u181-b13`, but should be `jdk-8u181+b13` I guess or at least `jdk-8u181-b13`. This every release name changes really suxxx.

**Comment by sxa555** [comment]
The openjdk repository we seed our source code from is called jdk8u (See http://hg.openjdk.java.net/jdk8u for the original source we pull from) therefore the `U` is correct.

Why do you want an extra `-` after jdk?

Ref "This every release name changes really suxxx." what are you seeing as inconsistent? Oracle put the build identifier (e.g. `192`) into their directories in the tarball too. The `+` character isn't good to use on Windows which is why we replace it with a `-`.

**Comment by alexhass** [comment]
> Why do you want an extra - after jdk?
This is how oracle names it.

I'm also not the fan of "+" in file names. In MSI setup I removed this crap, too.

My point main point is about consistency and readability and not change the name in every minor release. This is what happened in last ~3 minor releases. Every time I need to change scripts to build the MSI setup. This waste a lot of time for nothing.
