### ISSUE TITLE
Double-click on JAR doesn't launch the application

### ISSUE THREAD

**Issue by xtbe** [AdoptOpenJDK/openjdk-build#684]
When you double-click on a JAR the application it contains doesn't launch. 
This is different behaviour compared to the Oracle JDK/JRE. With this version this works.

Tested on Windows 10 x64

**Comment by karianna** [comment]
Was the Oracle JDK installed with an actual installer (MSI/EXE)?

**Comment by karianna** [comment]
Which Adopt binary did you try this with?

**Comment by xtbe** [comment]
Oracle JDK was installed via the EXE, removed via Add/Remove programs
Downloaded Adopt Binary was : OpenJDK8U-jdk-x64_windows_hotspot_8u181b13.zip

Think it's clear because it's not an exe/msi that some things are not registered. Think I got the ZIP file just because it was the default one presented on the page. When the installer is ready to be released it would probably be  good to default the installer to download or at least show it aside the zip file

**Comment by karianna** [comment]
Cool, yeah hopefully this is an installer issue that we can quickly address.

**Comment by sxa555** [comment]
(Thought I'd replied to this but apparently not)
Yeah I would expect that to be just because we're a ZIP and we're not performing any postinstall tasks to set up associations. I suppose we could provide a postinstall script to do it but if we get our installers production ready we can stuff like this in the installer instead

**Comment by gdams** [comment]
This is something that should be handled in the installers. Closing
