### ISSUE TITLE
Use the appropriate jdk tag when building OpenJ9 releases

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#748]
When looking for OpenJDK tags for OpenJ9 release builds, only tags of the appropriate `jdk` format should be used.

i.e.
https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/a98b32fb3bb156b8545235b7735bb2744d45c6d6/jdk/make/closed/autoconf/custom-hook.m4#L258

https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/6465e98ad3b609913c57cfe5b68a284396eddf98/closed/autoconf/custom-hook.m4#L311

The problem was that the https://github.com/ibmruntimes/openj9-openjdk-jdk11 repo added a tag (openj9-0.11r1), and this caused problems (see below) when (re)building the OpenJ9 0.11 release. However this tag should have been ignored.

https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-ppc64le-openj9/14/console
```
checking if packaged modules are kept... yes (default)
configure: WARNING: Option --with-milestone is deprecated and will be ignored.
configure: error: "openj9-0.11r1" is not a valid numerical value for VERSION_BUILD
configure exiting with result code 1
```

**Comment by pshipton** [comment]
@sxa555

**Comment by sxa555** [comment]
Relevant code is in getFirstTagFromOpenJDKGitRepo() in https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L478

**Comment by sxa555** [comment]
The logic around that makes it non-trivial to switch it to only check tags of a particular format with a `grep` for example.

In the case of the current failing builds it looks like the old (now deleted tag) has been removed from the repository but the clone on the machines (Except on Linux/s390x which I'd wiped for some reason a few days ago) still have the tag present in the clone and that hasn't been cleared (FYA @johnoliver @karianna).

I am now running https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/182/ with the `cleanWorkspaceBeforeBuild` option while will hopefully do a full reclone anywhere

**Comment by sxa555** [comment]
`CLEAN_WORKSPACE` option does not appear to have done what I expected it to - https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-openj9/28/console has not resulted in a full clone and the failure due to the deleted tag `openj9-0.11r1` is still preventing the builds from succeeding :-(

**Comment by sxa555** [comment]
CLEAN_WORKSPACE option does not appear to have done what I expected it to - https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-openj9/28/console has not resulted in a full clone and the failure due to the deleted tag openj9-0.11r1 is still preventing the builds from succeeding :-( Have contacted @johnoliver

**Comment by sxa555** [comment]
`CLEAN_WORKSPACE` option does not appear to have done what I expected it to - https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-openj9/28/console has not resulted in a full clone and the failure due to the deleted tag openj9-0.11r1 is still preventing the builds from succeeding :-( Have contacted @johnoliver

**Comment by sxa555** [comment]
Related: https://github.com/AdoptOpenJDK/openjdk-build/issues/725
Have cleared up the workspace for  in order to be able toprogress https://github.com/AdoptOpenJDK/openjdk-build/issues/744

**Comment by sxa555** [comment]
Yep I understand Peter - I'm just hijacking your issue to cover the immediate issue (since it's all symptoms of a problem under the category of the "unexpected tag") and won't close it once I've resolved it. The clean workspace option isn't doing what I expected (https://github.com/AdoptOpenJDK/openjdk-build/pull/761 may resolve) so have manually cleared all the workspaces on the machine. Now rerunning under https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline which will hopefully result in nightlies popping out again and let me get on fixing other stuff ;-)

**Comment by sxa555** [comment]
@pshipton Is the intent that your tags will always have `openj9` in them? I'm weighing up a whilelist (`^jdk*`) via blacklist (exclude `openj9`) approach here.

**Comment by pshipton** [comment]
@sxa555 It seems an undue restriction that ignored tags must contains `openj9`. We know the format of the openjdk release tags, as shown in the github links in the original description.

**Comment by sxa555** [comment]
See comment in the PR - the aarch64 tags are not always a direct `^jdk*u???-b??$` tag as a counter example
