### ISSUE TITLE
The README file gives no instructions for installing Cygwin

### ISSUE THREAD

**Issue by lwahonen** [AdoptOpenJDK/openjdk-build#755]
Windows can't run the makejdk-any-platform.sh (or any of the other tools) natively, and needs Cygwin or something similar installed. This dependency should be properly documented.

**Comment by sxa555** [comment]
FYI In general we have the ansible playbooks in https://github.com/AdoptOpenJDK/openjdk-infrastructure/tree/master/ansible/playbooks/AdoptOpenJDK_Windows_Playbook that cover all the prerequities needed to run the build which has generally been the master source of such information (although the Windows one isn't 100% complete just now but we are working on that)

I'm not against updating the README with a list as well but we just need to be conscious of the fact it will require updating things in two places when we add extra prerequisites.

**Comment by lwahonen** [comment]
I tried to find a ”for dummies” guide in that repo too, with little luck.

Right now, it seems that for *nix users making a build is a trivial exercise (git clone, makejdk-any-playform.sh). For Windows users, it looks extremely complicated.

I would assume many aspiring developers would prefer building the JDK on their workstation, not putzing around with Ansible build cluster automation.

**Comment by sxa555** [comment]
Nah we actually have a load of specific packages needed for UNIX based platforms too (In fact the list is longer), although it's a bit more likely that UNIX users will have more of the ones we need available by default.

The intention of ansible is to make it as easy as possible to set up machines in a suitable way as simply as possible without requiring people to do it manually, although the "as simply a possible" thing isn't quite there in practice for end users yet particularly on Windows so I'm perfectly happy to keep this issue as a valid one for someone to effectively convert the info in the ansible scripts into such a document until such time as we have a more sensible story in place, since yours is certainly a valid use case.

For the record, OpenJ9 provide some such documents already in their instructions in the documents at https://github.com/eclipse/openj9/tree/master/doc/build-instructions but bear in mind that some of what's in there will be a superset of what's required for HotSpot (.e.g. Clang/LLVM and FreeMarker)

**Comment by gdams** [comment]
docs updated. closing
