### ISSUE TITLE
OpenJ9 0.12.0 release build problems

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#882]
Looking at the OpenJ9 jdk8 0.12.0 release build u202-b08
https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=openj9

- the date is Jan 18, although OpenJ9 0.12.0 didn't ga until Jan 30 and was built at Adopt on Jan 30

- there is no 0.12.0 in the release name

- Linux x64 has 4 downloads, I assume 2 are for XL, but there is no label

**Comment by pshipton** [comment]
Looking at the jdk11 0.12.0 release build 11.0.2+9
https://adoptopenjdk.net/archive.html?variant=openjdk11&jvmVariant=openj9

- there are a number of extra downloads
i.e. Linux x64 has 6
Windows x64 has 4
macOS x64 has 6
etc

**Comment by sxa555** [comment]
Two of these symptoms are linked - I believe the "release" `jdk8u202-b08` was created on the 18th and the openj9 items were added to it today. The build scripts have had a number of issues today relating specifically to producting release OpenJ9 builds and we've had to work around them. Part of doing that involved having to compromise on the release name ... for now ... in order to get this out.

The LinuxXL one is a bit unexpected though ... We'll aim to look at it tomorrow but if you hover over the filename you can see that one of them is indeed the XL version.

FYI @johnoliver

**Comment by johnoliver** [comment]
I believe a lot of the issue you are seeing wrt the UI are due to the fact that you are no longer adding openj9 to the tag, your releases are getting added to the same release as hotspot. Previously as the name of the release is set by the tag your assets went into a separate release: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u192-b12_openj9-0.11.0
Which the Ui picks up on and displays in a nicer manner. #880 has a possible fix where it adds the additionalFileNameTag to the release name.

**Comment by lumpfish** [comment]
We ended up with the current names as a compromise - when we specified a releaseTag of jdk8u202-b08_openj9-0.12.0, an extra 8u202b08 was inserted into the filename, and if additionalFileNameTag was not used the windows executables for some reason were not executable.  @sxa mentioned https://github.com/AdoptOpenJDK/openjdk-build/issues/725.
See slack thread https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1548853841225600

**Comment by lumpfish** [comment]
Also, the openjdk test jobs check out the releaseTag (git clone --branch releaseTag), so jdk8u202-b08 had to be used to run those tests.  (Why --branch releaseTag is being issued looks wrong, the intent appears to be to check out the level of tests which matches the jdk being built, on which case it is the BRANCH parameter in the pipeline which should be cloned).

**Comment by sxa555** [comment]
Duplicates now removed (except on on the macos JRE, but that may be a caching issue. macosXL JDK11+J9 is not showing up yet, and s390x JDK11+J9 JRE has not been published for some reason.

**Comment by lumpfish** [comment]
Got ```/cygdrive/c/Users/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-windows-x86-32-openj9/sbin/build.sh: line 384: /tmp/openjdk-jdk8u-windows-x86-32-openj9/workspace/build/src/build/windows-x86-normal-server-release/images/j2sdk-image/bin/java: Accessing a corrupted shared library``` trying to create a release with these parameters:
releaseTag: jdk8u202-b08_openj9-0.12.1
branch: openj9-0.12.1
additionalFileNameTag: openj9-0.12.1

Could there be a setup issue related to building 32 bit on 64 bit Windows?

**Comment by karianna** [comment]
@ali-ince Might be your best bet there.

**Comment by sxa555** [comment]
@lumpfish See earlier comment where I referenced 725 and 680 - Windows has issues when you bulid with an extended tag name - if you can download and run the java executable it the symptoms are usually an error with "side by side" in the message. That's the whole reason we regrettably ended up with the additionalFileNameTag.
If we're going to resolve it we'll need to decouple `releaseTag` and have a `publishTag`

**Comment by lumpfish** [comment]
The jdk-11.0.2+9_openj9-0.12.1 release was built with
```
releaseTag: jdk-11.0.2+9_openj9-0.12.1
branch: openj9-0.12.1
additionalFileNameTag: openj9-0.12.1
```

The (64 bit) Windows build is OK on that build.  It is not clear to me from #725 and #690 what is the significant difference between that and building the jdk8u202-b08_openj9-0.12.1 release with
```
releaseTag: jdk8u202-b08_openj9-0.12.1
branch: openj9-0.12.1
additionalFileNameTag: openj9-0.12.1
```
where the (32 bit) Windows java got the "Accessing a corrupted shared library" message.

**Comment by lumpfish** [comment]
To summarise, the issues building the openj9 releases seem to stem from the use of releaseTag.

releaseTag currently seems to be the only way to dictate how the build appears in the openjdkxx-binaries repository (e.g. as jdk8u202-b08_openj9-0.12.1), and therefore on the AdoptOpenJDK download pages.

However, if used to set the release name to the desired value (e.g. as jdk8u202-b08_openj9-0.12.1)
a. The resulting Windows (jdk8u only?) builds do not work (java.exe does not run)
b. The Jenkins openjdk test jobs attempt to checkout a branch / tag with the releaseTag specified, which does not exist in the extensions repository from which the jdk is built
- This can be worked around (though painfully) by only building and submitting the tests as separate Jenkins jobs

The release naming convention of jdk8u202-b08_openj9-0.12.1 is required so that
1. openj9 releases are labelled with the correct release date in the openjdknn-binaries repository (they are likely to be released on a different data to the openjdk-hotspot releases)
2. releases containing updates to the openj9 component can be produced at more regular intervals than the openjdk quarterly updates, which in turn requires a new 'key' in openjdkxx-binaries.

**Comment by karianna** [comment]
#884 and #886 will help with this

**Comment by sxa555** [comment]
Also "random" checksum publish failure issues: https://github.com/AdoptOpenJDK/openjdk-build/issues/891

**Comment by aahlenst** [comment]
Improvements have landed, we haven't had similar problems with recent releases.
