### ISSUE TITLE
ARM (jdk8) build artifact has incorrect name

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#91]
From Stuart Monteith:

Also, the build has been named
"OpenJDK8_arm64_Linux_201725040754.tar.gz". The "arm64" part should be
"aarch64". While the "arm64" terminology isn't encouraged, and the VM
identifies itself as os.arch="aarch64", it also conflicts with the two
64-bit ARM backends that exist in JDK9. The Unified Oracle backend
identifies itself as "arm64", while the original OpenJDK 64-bit ARM
port is "aarch64".

**Comment by stooart-mon** [comment]
Current you can configure and build two different aarch64 backends. 
You can all configure with:
  `  configure --with-cpu-port=aarch64|arm64`
If you select aarch64 - you get the port that was originally done in OpenJDK. If you select "arm64" you get the Oracle backend that was contributed by them in December 2016. 
The aarch64 port is the default, so that is what the build system will be producing. In addition, the aarch64 port has always identified itself as such, so that is consistent.

**Comment by vielmetti** [comment]
I'll defer to Stuart on naming, so long as we're consistent and predictable it should all be fine.

**Comment by karianna** [comment]
@vielmetti and @stooart-mon Thank you both!  We'll go aarch64 then.  I've made the change on Jenkins.  Will keep this issue until we see a built artifact.

@Joe-Brady Can you do the honours for the api and website?

**Comment by Joe-Brady** [comment]
No problem. Should have time to sort this tomorrow.
