### ISSUE TITLE
Windows x64 11.0.2+9 crashes running "java -version"

### ISSUE THREAD

**Issue by marco-schmidt** [AdoptOpenJDK/openjdk-build#969]
Hi all!

We have a crash of OpenJDK11U-jdk_x64_windows_hotspot_11.0.2_9.zip on a customer machine running simply "java -version".

On our test environment for that customer we have no problem. The two machines are running similar but not identical Windows versions (Datacenter vs. Standard):

(customer, crashes)
systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows Server 2016 Datacenter
OS Version:                10.0.14393 N/A Build 14393

(our system, working)
systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows Server 2016 Standard
OS Version:                10.0.14393 N/A Build 14393

Crash file log [hs_err_pid7196.log](https://github.com/AdoptOpenJDK/openjdk-build/files/2979582/hs_err_pid7196.log) attached. Any idea what might cause this or how to fix it?

Thanks in advance,
Marco

**Comment by karianna** [comment]
Hi Marco, 

1. Has the customer tried an alternative OpenJDK provider? I want to quickly see if this is an upstream issue.
2. Is it also possible to get us access to the heap dump itself?
3. Can your customer try without having the CompressedOops flag switched on?  It seems to be suppressing some reporting and could also be the root cause.

Paging @ali-ince to take over if we can get more info :-)

**Comment by marco-schmidt** [comment]
Hi Martijn, thanks for the quick response. We will try another OpenJDK version for comparison. To produce the heap file without compressed oops, we would run
java -XX:-UseCompressedOops -version
to disable it on the customer machine? We did not turn on compressed oops explicitly, it seems to be on by default.

**Comment by karianna** [comment]
> Hi Martijn, thanks for the quick response. We will try another OpenJDK version for comparison. To produce the heap file without compressed oops, we would run
> java -XX:-UseCompressedOops -version
> to disable it on the customer machine? We did not turn on compressed oops explicitly, it seems to be on by default.

Correct, the JVM ergonomics may have switched it on.

**Comment by marco-schmidt** [comment]
Another Java 11 has no issues when run on the same machine:
https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_windows-x64_bin.zip from https://jdk.java.net/11/

We've created another heap dump and log file running AdoptOpenJDK's 11.0.2+9 like this:
java -XX:-UseCompressedOops -version
Zipped both files and made them available at https://www.dropbox.com/s/s6sa3ycyppt9s6x/openjdk-build-issue-969.zip?dl=0

**Comment by ali-ince** [comment]
Hi Marco,

I have spent some time trying to reproduce this but couldn’t have a failure at all.

I believe we have two options here;

1) Create a jdk11u build from the same tag with visual studio 2017, which will show if it’s related with platform components or not.
2) Create a jdk11u build using the current setup with debug symbols included so that we can gather more information about the failure and it’s location.

I’ll suggest taking both approaches, if that sounds reasonable for you and your customer too.

I will be half offline in the following days and planning to spend some time on these approaches. Is it ok if we could switch to an email conversation until we get this resolved to facilitate a faster communication?

Thanks,

Ali

**Comment by marco-schmidt** [comment]
Hi Ali,

we could run both versions to further try to identify the problem.

I don't mind taking this to mail, how would I contact you?

Thanks for your help,
Marco

**Comment by ali-ince** [comment]
Hi Marco,

I have sent an e-mail to the e-mail address that's shown on your git commits, please let me know if you didn't receive any.

Thanks,

Ali

**Comment by marco-schmidt** [comment]
I got the mail and replied.

**Comment by marco-schmidt** [comment]
Cannot reproduce problem anymore. It seems like the one machine where this happened was changed in some way, or the JDK content was not properly rolled out. Thanks again to everyone helping to find the issue.
