### ISSUE TITLE
Stabilise AIX builds (ramdisk space issue)

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#998]
Currently things are being left around on the AIX build machines in the ramdrive which has limited space.

Some of the dump files already have an issue covered by https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/693 which proposes redirecting them from the ramdisk, but we also have some of the workspaces under `build-scripts` being left and they can be up to 5Gb each with JDK11/12.

I have created https://ci.adoptopenjdk.net/view/work%20in%20progress/job/sxa_monitor_AIX_ramdisks/ which will check the amount of space use and will be optionally able to remove anything lying around, and I will probably set this up on a regular scheduled to allow us to determine when issues are occurring.

Running that job on `build-osuosl-ppc64-aix-71-2` has failed due to `/tmp` being full preventing jenkins from writing it's temporary script there (Ref: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/sxa_monitor_AIX_ramdisks/label=build-osuosl-ppc64-aix-71-2/1/console)

**Comment by sxa555** [comment]
Cleared up `/tmp`, run the job on `-2` (not yet `-1` as it's in use) and have initiated the following pipelines which will re-run 8/11/12 nightlies to verify them (Currently all are red):
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/498/
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/371/
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk12-pipeline/106/

**Comment by sxa555** [comment]
Also seeing a large number (2.2M) of files `/tmp/sh-np-*` which are pipes owned by the jenkins user on `-2` that don't seem to be getting cleaned up.

**Comment by sxa555** [comment]
Most builds currently failing due to https://github.com/AdoptOpenJDK/openjdk-build/issues/1005

**Comment by sxa555** [comment]
Have adjusted [build-osuosl-ppc64-aix-71-2](https://ci.adoptopenjdk.net/computer/build-osuosl-ppc64-aix-71-2) to use a workspace under `/home/jenkins/workspace` for now. With the builds taking over 3 hours at present (Not sure why) I'm going to try just moving them to see how much of a difference it makes since stability is probably more important right now.

**Comment by sxa555** [comment]
Seems to be a definite slowdown on `-2` which is the box shared with test at the moment.

Release | Build time
------------ | -------------
JDK8/HotSpot | 1h18 (`-1`)
JDK8/OpenJ9 | 1h29 (`-1`)
JDK11/HotSpot | 3h01 (`-2`)
JDK11/OpenJ9 | 1h30 (`-1`) or 2h40 (`-2`)

I am running a test with the workspace on the disk instead of a ramdrive on `-2` to see how much of a difference that is now making. Will update this comment when that's complete.

**Comment by sxa555** [comment]
Slowness on `-2` was due to an orphaned jenkins agent process that was holding the load on the machine at about 12 even when it wasn't doing anything. Have now cleared that up and it should now be running much better.

**Comment by sxa555** [comment]
Freezes of jobs on AIX - killing the following running for 5 days:
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk12u/job/jdk12u-aix-ppc64-hotspot/62/
```
wrapper script does not seem to be touching the log file in /ramdisk0/build/workspace/build-scripts/jobs/jdk12u/jdk12u-aix-ppc64-hotspot@tmp/durable-efa56f5d
(JENKINS-48300: if on an extremely laggy filesystem, consider -Dorg.jenkinsci.plugins.durabletask.BourneShellScript.HEARTBEAT_CHECK_INTERVAL=86400)
```

**Comment by aixtools** [comment]
a) with regard to title - iirc /ramdisk is no longer being used
b) I have done some maintenance to make sure /tmp does not overrun with things left behind by builds.

imho: need to get the (OSUOSL) AIX partitions under load - so any open issues can be addressed.
